serde-rs/json

- json/src/lib.rs
Added an example struct for the example JSON.
> Add an example struct corresponding to example json

- json/src/value.rs
Refs #62 
I can add some tests, but implementation seems trivial. Tests fail on `nightly`, but this seems unrelated.
> feat(value): impl Display and FromStr traits

- json_tests/Cargo.toml
(The serde_json version was already bumped to 0.7.1 in #41)
This release includes:
- RFC6901 JSON pointer (#41)
- Bugfix related to missing_field (#61)
- Improved ergonomics: ToValue, FromStr, ToString (#63 and #64)
> Release 0.7.1

- json/src/ser.rs
> Remove escape_bytes

- json/src/builder.rs
- json_tests/tests/test_json_builder.rs
> Rename Object/ArrayBuilder::unwrap() to build()

- json/src/value.rs
> Rename Value::as_* functions

- json/src/builder.rs
- json/src/de.rs
- json/src/error.rs
- json/src/lib.rs
- json/src/ser.rs
- json/src/value.rs
Clippy was not running because the Travis build used the "clippy" feature and clippy was cfg'd with the "nightly-testing" feature.
> Fix clippy lints

- .travis.yml
- json/Cargo.toml
- json_tests/Cargo.toml
> Rename feature "nightly-testing" to "unstable-testing"

- json/Cargo.toml
- json/src/ser.rs
- json/src/value.rs
- json_tests/Cargo.toml
- json_tests/tests/test_json.rs
Update for serde-rs/serde#437.
> New Serializer API

- README.md
To prevent people from copy-pasting this.
I know this means it needs to be updated at each major release, but I hate
wildcard dependency versions and one of my goals in life is to hunt them down
and replace them to restore sanity (as defined by SemVer) ;)
> Explicit version in Readme

- json/src/de.rs
> Remove whitelisted clippy lint fixed in 0.0.80

- .travis.yml
- json/Cargo.toml
> fix build for preserve_order

- json/src/error.rs
- json/src/read.rs
> Fix new lints in clippy 0.84

- json/src/builder.rs
- json/src/value.rs
- json_tests/tests/test_json.rs
> Do not panic in to_value

- json/src/lib.rs
- json/src/map.rs
- json/src/number.rs
- json/src/value.rs
- json_tests/tests/test_json.rs
- json_tests/tests/test_json_builder.rs
> Extract serde_json::Map and serde_json::Number opaque newtypes

- json/src/ser.rs
- json_tests/tests/test_json.rs
> Extend Formatter with more callbacks

- json/src/number.rs
- json/src/value.rs
> Derive Debug for Value

- json/Cargo.toml
- json/src/ser.rs
- json/src/value.rs
- json_tests/Cargo.toml
Fixes #151. Requires https://github.com/serde-rs/serde/pull/716.
> Serialize T by ref

- json/src/map.rs
> Index into Map

- json/src/value.rs
> Impl Default for Value

- json/src/value.rs
- json_tests/tests/test.rs
by transforming them to strings.
Fixes #221
> Serialize Map with integer keys

- json/src/value.rs
- json_tests/tests/test.rs
> Implement PartialEq for Value

- json/src/macros.rs
> Refactor json_internal macro to need no helper macros

- json/src/error.rs
- json/src/map.rs
- json/src/number.rs
Equivalent of https://github.com/serde-rs/serde/pull/731.
> No tuple structs with private fields in public API

- json/src/macros.rs
- json_tests/tests/test.rs
> Generalize json! macro to ToJson

- json/src/map.rs
- json/src/value.rs
Fixes #247.
cc @garrensmith who asked about this in IRC (if your username is **garren**)
> IndexMut for Map and Value

- json/src/value.rs
This is how I spend my lunch breaks! 😆 (Mostly copy-pasta, though.)
I'd love to `impl<T: Into<String>> From<T> for Value` and probably also `impl<T: Iterator<Item=I>, I: Into<Value> From<T> for Value`. Maybe with specialization?
Fixes #241
> Implement a bunch of `From`s

- json/src/de.rs
- json/src/error.rs
- json/src/read.rs
Usecase described in #256. Also see the included documentation.
> Fix #256: support deserializing strings with arbitrary bytes

- json/src/number.rs
- json/src/value.rs
- json_tests/tests/test.rs
> Deserializer for &Value

- json/src/macros.rs
- json_tests/Cargo.toml
- json_tests/deps/Cargo.toml
- json_tests/tests/compiletest.rs
- json_tests/tests/ui/missing_colon.rs
- json_tests/tests/ui/missing_colon.stderr
- json_tests/tests/ui/missing_value.rs
- json_tests/tests/ui/missing_value.stderr
- json_tests/tests/ui/not_found.rs
- json_tests/tests/ui/not_found.stderr
- json_tests/tests/ui/parse_expr.rs
- json_tests/tests/ui/parse_expr.stderr
- json_tests/tests/ui/parse_key.rs
- json_tests/tests/ui/parse_key.stderr
- json_tests/tests/ui/unexpected_colon.rs
- json_tests/tests/ui/unexpected_colon.stderr
- json_tests/tests/ui/unexpected_comma.rs
- json_tests/tests/ui/unexpected_comma.stderr
- json_tests/tests/ui/update-references.sh
- travis.sh
> Compile-fail tests for the json macro

- json/src/value.rs
Possible implementation of #279
> Pretty print Value when alternate formatting requested

- json/src/macros.rs
- json/src/value.rs
- json_tests/tests/test.rs
> Remove ToJson trait

- appveyor.yml
- travis.sh
> Set up AppVeyor

- json/src/ser.rs
Fixes #268. Identical to #269.
> Pass &str to write_string_fragment

- json/src/ser.rs
Fixes #274. Unfortunately the original motivation doesn't apply anymore because of #268 which makes it so that implementing io::Write for the Adapter struct would be unsafe (now that the unsafe is in our code rather than the code of the person implementing Formatter). Even so, it still doesn't make sense for a formatter to fail for any reason other than IO.
> Return io::Error from formatter methods

- json/src/de.rs
- json/src/error.rs
- json_tests/tests/test.rs
> Require array or object in StreamDeserializer

- src/error.rs
- tests/test.rs
Addresses #319.  I'm not sure if the change handles all the relevant cases.
> Better invalid type error message

- src/value/partial_eq.rs
- tests/test.rs
PartialEq for bool seems useful. I appended it to this https://github.com/serde-rs/json/pull/235.
> Implement PartialEq for bool

- src/de.rs
- src/read.rs
- tests/test.rs
> Optimize deserialize_ignored_any

- README.md
> README - add additional info about untyped Example - closes #367

- src/de.rs
- tests/stream.rs
Currently StreamDeserializer only supports objects and arrays, because it couldn't handle things like `truefalse` properly before. This PR changes the behavior of the parser so that it checks after parsing an identifier whether there's any trailing characters that aren't one of ` \n\t\r"[]{},:` or EOF, and if there is it will give an error. This means it will error immediately when parsing `truefalse` instead of first emitting `true` followed by an error.
Related: https://github.com/serde-rs/json/pull/301
cc @dtolnay
> Support top-level primitives in StreamDeserializer

- src/de.rs
This should be false, not true
> Fix falsey typo

- src/value/mod.rs
This is equivalent to `Option::take` method.
> Add `Value::take` method

- src/de.rs
Addresses issue #420 
This library has been super helpful to me! Thank you for the hard work 🎈 
I grepped for instances of `pos` and replaced the ones which seemed relevant. I only replaced full abbreviations, leaving things like `exp_pos` alone. I also ran the tests locally, though I didn't check that they passed for every single toolchain.
> Replace relevant instance of "pos" with "positive"

- src/de.rs
Addresses #420.
Just a followup to #425, fixing the few remaining instances.
> Replace instances of "exp_pos" with "exp_positive"

- README.md
Fixes #422.
<a href="https://blog.rust-lang.org/2017/02/02/Rust-1.15.html"><img src="https://img.shields.io/badge/rustc-1.15+-bc71d0.svg" alt="Rustc Version 1.15+" width="300"></img></a>
> Rustc version badge

- src/map.rs
> Add values_mut() iterator for serde_json::Map

- src/map.rs
> Implement order-independent equality

- Cargo.toml
- src/de.rs
- src/number.rs
- src/ser.rs
- src/value/de.rs
- tests/test.rs
> Basic support for i128 and u128

- .travis.yml
- Cargo.toml
- src/lib.rs
- src/map.rs
- src/read.rs
- src/value/mod.rs
- travis.sh
This was surprisingly easy :confused:.
> Use IndexMap instead of LinkedHashMap

- src/de.rs
- tests/test.rs
> Produce eof error on truncated ident

- src/read.rs
`serde_json` is slower than expected when parsing long string filled with hexadecimal escape sequences. I discovered the problem while testing with following benchmark case:
https://raw.githubusercontent.com/devinus/poison/master/bench/data/utf-8-escaped.json
`serde_json` is two times slower than moderately optimized c++ implementation, and here's performance profile of `serde_json` for the testcase, captured with `perf record`.
```
#
25.81%  6_scheduler  librjs.so           [.] serde_json::read::parse_escape
25.19%  6_scheduler  librjs.so           [.] serde_json::read::decode_hex_escape
16.59%  6_scheduler  librjs.so           [.] serde_json::read::next_or_eof
11.78%  6_scheduler  libc-2.27.so        [.] __memcpy_ssse3
11.27%  6_scheduler  librjs.so           [.] …
```
> specialize hexadecimal sequence decoding

- src/read.rs
- tests/test.rs
Improve error position for string that contains invalid characters or invalid hex sequence.
> Improve error position for string that contains invalid characters

- src/value/de.rs
- tests/test.rs
Fixes https://github.com/serde-rs/json/issues/503.
> Allow map key to be borrowed from &Value

- src/value/ser.rs
- tests/test.rs
> Fix integer128 serialize

- src/ser.rs
- tests/test.rs
> Quotes around u128 in map key

- Cargo.toml
- src/number.rs
- tests/regression.rs
- tests/regression/issue520.rs
- tests/regression/mod.rs
> Fix adjacently tagged f32 roundtrip regression

- src/de.rs
- src/lib.rs
- src/read.rs
- tests/stream.rs
> Return None after stream deserializer has failed

- fuzz/.gitignore
- fuzz/Cargo.toml
- fuzz/fuzz_targets/from_slice.rs
This commit adds initial cargo fuzz infrastructure in parallel with integration into the OSS-Fuzz project.
> Added from_slice fuzzer and OSS-integration.

- src/value/from.rs
This feels like an API omission if I am not missing something.
> Allow collecting an iterator of pairs into JSON object

- src/value/mod.rs
just a minor ergonomic improvement to the documents on the web
> make a html link in the doc comments

- src/de.rs
> Restore compatiblity with older rustc after PR 786

- src/value/de.rs
These 3 are all along the lines of #792.
> Delete several other superfluous Deserializer impls

- src/de.rs
- tests/test.rs
> Parse -0 as float -0.0 instead of integer 0

- src/de.rs
- tests/regression/issue953.rs
> Require at least one digit after decimal point

- src/macros.rs
I tried to do this, and while you can piece together the way to do this from the interpolation comment, it's the one piece of direct JSON syntax that isn't immediately obvious.
> Add an example of producing a Null in a json! literal

- src/de.rs
- src/value/de.rs
- tests/test.rs
> Insert check for whitespace surrounding numeric map key deserializing from Value

- src/raw.rs
> IntoDeserializer for &RawValue

- .github/workflows/ci.yml
As per https://github.com/serde-rs/json/pull/1173#pullrequestreview-2231890262.
> Test on BE and 32-bit platforms on CI via Miri

- src/number.rs
Followup to https://github.com/serde-rs/json/pull/1141.
> Allow arbitrarily large i128 in arbitrary_precision mode

- src/number.rs
- src/value/de.rs
Followup to https://github.com/serde-rs/json/pull/1141.
> Add Number u128 conversions

- src/value/from.rs
> Implement From<[T; N]> for Value

- src/value/ser.rs
Much like how serialize_seq uses Vec::with_capacity.
> Use Map::with_capacity in value::Serializer::serialize_map

- .github/workflows/ci.yml
- Cargo.toml
Unblocks https://github.com/serde-rs/json/pull/1285.
> Raise required compiler to Rust 1.61
