json/src/de.rs
There were come copy-paste errors in the `from_*` functions.
=> fix bug in documentation

json/Cargo.toml
`num` pulls in deps for features that `serde` doesn't need, so opt-out of them.
=> fix(dependencies): Opt-out of default features of `num`

json/src/lib.rs
Fixes my formatting mistake introduced in https://github.com/serde-rs/json/pull/15 (sorry!) and also adds a renaming example.
=> docs(typos): Add necessary whitespace, add renaming example

json/src/de.rs
=> Minor typo: Interator => Iterator

json/src/ser.rs
Unable to set the indent constant for a new PrettyFormatter instance, nor reuse PrettyFormatter in an external crate outside of the serde_json::ser::Serializer.
If you kept these private on purpose because you weren't sure of the API choice for setting the indent, let me know.
=> Make the constructor methods publicly visible for the PrettyFormatter.

json/src/de.rs, json_tests/tests/test_json.rs
Currently there is a fixme that was never fixed, which causes `-0` to explode with an overflow.
=> Fix negative zero

json/src/value.rs
This allows to_value() to accept &str arguments directly.
=> Remove the Sized bound on to_value<T>()

json/src/de.rs, json_tests/tests/test_json.rs
This resolves #22, resolves #29, and resolves #30.
* The reported error code is now `MissingField`, not `ExpectedSomeValue`.
* A missing `()` field now causes a `MissingField` error.
* A missing `Vec<_>` field now causes a `MissingField` error.
Tests have been updated to check these cases.
=> Fix: Report correct error code for missing field

json/src/de.rs, json/src/lib.rs, json_tests/tests/test_json.rs
Many modern web APIs return their data as stream of (sometimes newline
delimited) JSON values. This commits add handy function `parse_stream`
that returns Iterator over parsed values.
This feature has some drawbacks or issues:
* I'm not sure, whether it's good idea to expose `JSONStream` type, but it seems you cannot currently return abstract `Iterator`
* Ideally, we should accept `io::Read`, but I couldn't get it to work, unfortunately: `expected 'Iter', found `std::io::Bytes<R>`
* The hardest one — naming, — not sure, how to name iterator and helper function. 
Commit contains tests (and they are passing!) 
WDYT?
=> Add helper function to parse stream of json values

json_tests/Cargo.toml, json_tests/benches/bench.rs, json_tests/build.rs, json_tests/tests/test.rs, json_tests/tests/test_json.rs
[Indoc](https://github.com/dtolnay/indoc) takes a string literal and un-indents it so the leftmost non-space character is in the first column. Let me know whether you think this is valuable.
*Before:*
```rust
concat!(
"[\n",
"  false,\n",
"  null,\n",
"  [\n",
"    \"foo\\nbar\",\n",
"    3.5\n",
"  ]\n",
"]"
)
```
*After:*
```rust
indoc!(r#"
[
false,
null,
[
"foo\nbar",
3.5
]
]"#
)
```
=> Use indoc for JSON document literals in test

json/Cargo.toml, json/src/value.rs, json_tests/tests/test_json.rs
Add a method `pointer(&str)` to `Value`. Deprecate `lookup(&str)`.
Bump version to 0.7.1.
Closes #9 
Notes:
* It should be possible to add a `pointer_mut(&str)` method to Value. This would allow to add and modify values. (Maybe even a delete method) I failed to add such a method because of borrow checker.
* Should [RFC6902 JSON Patch](https://tools.ietf.org/html/rfc6902) be implemented or is this something for a separate crate? (Patch is based on Pointer)
=> feat(value): implement RFC6901 JSON Pointer

json/src/value.rs
The logic for treating missing fields differed between the utf8 deserializer and the `Value` one, and missing fields would be incorrectly reported as an "invalid type" error instead. This makes the two deserializers consistent. I believe the "deserialize from unit" logic was just left over from before `deserialize_option` was a thing, and therefore isn't necessary anymore?
Fixes #50
=> fix(value): Missing field error when deserializing from Value

README.md, json/Cargo.toml, json/src/builder.rs, json/src/lib.rs, json/src/value.rs, json_tests/tests/test_json.rs, json_tests/tests/test_json_builder.rs
I've added a PR for #54 
linked-hash-map needs to be released (probably version = "0.0.11") before this can be merged.
I had to use `linked_hash_map::Iter<'a, String, Value>` as a replacement for `btree_map::IntoIter<String, Value>`. This in turn required me to clone keys/values in `deserialize_enum` and `visit_key`. I'm not sure this is the best solution.
Also since I'm new to Rust and this is my very first PR please check my code thoroughly :)
=> add preserve_order feature

.travis.yml
This takes us from 28 minutes to 5 minutes. The biggest savings is not compiling all of Clippy + Syntex in release mode for the benchmark.....
=> Trim down the Travis build

json/src/ser.rs, json_tests/tests/test_json.rs
This fixes fix #65 by raphlinus.
All I did was merge the test file correctly. 
In regard to similar requests #58 and #66, is there a preferred solution?
=> Correctly escape ASCII control characters in strings

json/src/ser.rs
I am working on porting [this benchmark](https://github.com/miloyip/nativejson-benchmark#stringify-time) to Rust. This change makes about 20-30% difference in citm_catalog.json and twitter.json which are heavy on strings.
Side note: together with #87 and #88 this brings us within 10% of RapidJSON which is the fastest C/C++ implementation (as measured by that benchmark).
=> Speed up string printing

json/src/de.rs, json/src/ser.rs, json/src/value.rs, json_tests/tests/test_json.rs
Ref https://github.com/serde-rs/serde/issues/251. This is a rebase of #37 with more tests to ensure backward-compatibility with the current format.
=> Serialize unit variants as name only

json/src/de.rs, json/src/lib.rs, json/src/read.rs, json_tests/tests/test_json.rs
This improves parser performance by 30-60% (that's right, more than 2x faster for many inputs). Performance when reading from other types of iterators is not affected.
The tests are going to require a Serde release containing https://github.com/serde-rs/serde/pull/422 and https://github.com/serde-rs/serde/pull/423.
=> Specialize parser for Iter=&[u8]

json/src/de.rs, json/src/read.rs, json_tests/tests/test_json.rs
When deserializing from a `&str`, we can assume that the input is valid UTF-8 so don't need to do additional checks.
This makes the [Twitter benchmark](https://github.com/serde-rs/json-benchmark) about 15% faster because it is heavy on strings.
=> Specialize parse_string for Iter=&str

json/src/de.rs, json_tests/tests/test_json.rs
Fixes #108 and fixes #109.
Parse floats as a u64 until the end, then use a lookup table to scale by the correct power of 10. This is faster and also more accurate. The old code used repeated division by 10 which is so inaccurate that `1.0 / 10.0 / 10.0 / 10.0 / 10.0 / 10.0 / 10.0 != 1e-6`.
This is about 40% improvement on the [Canada benchmark](https://github.com/serde-rs/json-benchmark) (almost twice as fast).
=> Speed up float parsing

json/src/value.rs, json_tests/tests/test_json.rs
=> Fix unexpected brackets in to_value of a newtype struct

json/src/ser.rs
To keep API compatibility somewhat, I extracted a function `format_escaped_str` separate from `escape_str` to support sending in a custom formatter in my last PR #143.  However I forgot to update the `Serializer` to use this function so all strings would always be formatted with the `CompactFormatter` erroneously.  This addresses that issue.
=> Forward the correct formatter instance to format_escaped_str

json/src/value.rs
This is backwards compatible as there exists an implementation of Serializable for `&'a T` where T: Serializable.
It makes the function a lot more friendly to use in iterator adaptors, option and result consumers, etc.
=> take argument to `Value::to_value` by value

json/src/ser.rs
Write is an object safe trait, so users can construct an `&mut Write`
object. However, the `to_writer` and `to_writer_pretty` functions take an
`&mut W: Write`. In order to allow users to pass `&mut Write` objects to
these functions, their `W` parameter is now constrained `?Sized`, to allow
it to be a dynamically sized type (such as a trait object).
=> Allow trait objects in the to_writer function.

json/src/value.rs, json_tests/tests/test_json.rs
See https://tc39.github.io/ecma262/#sec-serializejsonproperty
Fixes #155 
--
As a heads up, I'm pretty new to rust so if I'm off-track with this PR I apologize! I ran the tests using the nightly compiler (as that was the only one that seemed to allow the given compiler features).
=> Ensure value::Serializer emits Value::Null for non-finite floats

json/src/lib.rs
cf https://docs.serde.rs/serde_json/value/enum.Value.html
=> Typo fixed: it's called Bool, not Boolean

json/src/ser.rs, json_tests/tests/test_json.rs
Fixes https://github.com/Aaronepower/tokei/issues/83. cc @Aaronepower
=> Allow map keys that are effectively strings

json/src/value.rs, json_tests/benches/bench_json.rs, json_tests/tests/test_json.rs
I was thinking that JSON Patch support would be useful, and saw the Issues for that and for `pointer_mut` support. #68 `pointer_mut` seemed necessary for implementing Patch, so I took a swing at it! This is my first open-source Rust PR so criticism is welcome but be gentle, haha!
I moved `pointer` into a new trait (`Pointer`) and added `pointer_mut` to it as well.  To maintain symmetry I also added a `pointer_owned` method that consumes the `Value` and returns an owned `Value`. Because of the new trait this is a breaking change (you need to import the trait for `pointer` to work now.)
Unit tests were added and all pass, documentation was added but is mostly just copy-paste from the existing code. I also wrote a benchmark to verify that the changes I made to `pointer` weren't slower than …
=> Implement issue #68 - add pointer_mut

json/src/ser.rs
Maybe we should run unit tests against an io::Write that returns Ok(0) on every other call...
=> Require newline to be written successfully

json/src/value.rs, json_tests/tests/test_json.rs
Fixes #189. This has been deprecated since serde_json 0.7.1.
=> Remove Value::lookup

json/src/macros.rs, json_tests/Cargo.toml, json_tests/tests/test.rs, json_tests/tests/test.rs.in
Two things:
- The vec![...] optimization pointed out by @bluetech in https://github.com/serde-rs/json/pull/207#issuecomment-274555826,
- Allow expressions inside an array or object to contain commas at what looks like the top level.
The second case is addressing expressions that look like `...<a , b>...`. Unlike () [] {}, the angle brackets are not a single token tree so the comma looks like an array element separator / map entry separator to the previous implementation. Here I rely on the $expr parser to fix this case.
Map keys are still broken with respect to commas inside <...> because follow-set rules prohibit parsing $expr followed by colon. I am not concerned about this because I expect interpolation inside map keys to be rare and simple. The error if it happens is "expected …
=> TT-muncher improvements

json/src/value.rs
We could do IndexMut too but I looked at [what json-rust does](https://github.com/maciejhirsz/json-rust/blob/v0.11.5/src/value/mod.rs#L546-L566) and it is pretty bizarre. I think this is enough to get us most of the value of straightforward indexing.
=> Implement indexing into Value

json/src/de.rs, json/src/read.rs
```rust
pub struct Client {
reader: StreamDeserializer<serde_json::Value, Bytes<TcpStream>>,
}
fn f(c: Client) { /* ... */ }
```
```rust
pub struct Client<D> {
reader: D,
}
fn f<D>(c: Client<D>) where D: Iterator<Item = Result<serde_json::Value, serde_json::Error>> { /* ... */ }
```
```rust
pub struct Client<R> {
reader: StreamDeserializer<R, serde_json::Value>,
}
fn f<R>(c: Client<R>) where R: serde_json::de::Read { /* ... */ }
```
Fixes #234. cc @sorccu
=> Expose serde_json::de::Read to use in where clauses

json/src/de.rs, json/src/read.rs
@dflemstr can you confirm that this would fix your use case in #259?
=> Expose the various Read implementations

json/Cargo.toml, json/src/lib.rs, json/src/map.rs
=> Add entry API and expose map module

json/src/de.rs, json_tests/tests/test.rs
I'm sorry, my fix for #256 had two errors:
* I forgot to clear the str_buf before parsing bytes. This results in incorrect parses.
* Somehow, my patch regressed performance by a lot. I'm not sure why this is the case, but using `peek_or_null` instead of `peek` fixes the issue.
The release with the previous PR should probably be yanked at crates.io. I apologize for the trouble, I should have verified my code better.
I also added a test for this particular failure case.
=> Fix regressions introduced by #256 fix

json/src/macros.rs
If serialization fails, the ``json!`` macro can panic.  This is presumably intended (there is an explicit unwrap of ``serde_json::value::to_json()`` in ``macros.rs``), but the documentation at https://docs.serde.rs/serde_json/macro.json.html does not mention that a panic is possible.  If this macro is meant to panic in such a case, I think it makes sense to document this.
Panic example:
```rust
extern crate serde;
#[macro_use]
extern crate serde_json;
use serde::ser::Error;
struct Foo {
foo: usize,
}
impl serde::Serialize for Foo {
fn serialize<S: serde::Serializer>(&self, _: S) -> Result<S::Ok, S::Error> {
Err(S::Error::custom("error"))
}
}
fn main() {
let foo = Foo { foo: 0 };
// Prints out an error message.
println!("{:?}", serde_json::to_string(&foo));
// Panics.
json!([foo]);
}
``` …
=> Document the fact that json! can panic.

json/src/de.rs, json/src/error.rs, json/src/read.rs, json_tests/tests/test.rs
Fixes #245. @vorner, @kixunil who were interested in that ticket and @mitsuhiko who was interested in line and column, does this look like it would work for your use cases?
---
---
=> Extend the Error API with line, column, category

json/Cargo.toml, json/src/de.rs, json/src/map.rs, json/src/number.rs, json/src/read.rs, json/src/value.rs, json_tests/Cargo.toml, json_tests/tests/test.rs
This PR enables serde_json to deserialize data structures that borrow from the input &str or &[u8].
Requires https://github.com/serde-rs/serde/pull/826.
=> Zero copy deserialization

src/de.rs, src/iter.rs, src/read.rs, tests/stream.rs, tests/test.rs
Fixes #183.
The byte offset is the number of bytes so far deserialized into a successful `T`. If a stream deserializer returns an EOF error, new data can be joined to `old_data[stream.byte_offset()..]` to try again.
```rust
let data = b"[0] [1] [";
let de = serde_json::Deserializer::from_slice(data);
let mut stream = de.into_iter::<Vec<i32>>();
assert_eq!(0, stream.byte_offset());
println!("{:?}", stream.next()); // [0]
assert_eq!(3, stream.byte_offset());
println!("{:?}", stream.next()); // [1]
assert_eq!(7, stream.byte_offset());
println!("{:?}", stream.next()); // error
assert_eq!(8, stream.byte_offset());
// If err.is_eof(), can join the remaining data to new data and continue.
let remaining = &data[stream.byte_offset()..];
```
cc @vorner @ShepMaster who were interested in #212.
=> Expose number of bytes processed by StreamDeserializer

src/de.rs, src/read.rs, src/value/de.rs, tests/test.rs
Fixes https://github.com/serde-rs/json/pull/177#issuecomment-297780506 by deserializing map keys with a special Deserializer that allows the same types that the map key Serializer allows.
cc @arthurprs
=> Allow integers to be used as map keys again

src/de.rs
All these functions end up calling `visit_f64` so rewriting these functions to avoid dependence on the visitor type `V` is a no-brainer:
- `parse_long_integer`
- `parse_decimal`
- `parse_exponent`
- `parse_exponent_overflow`
- `visit_f64_from_parts`
Slightly alleviates #314.
---
Benchmarks on the [minimal Pandoc example](https://github.com/serde-rs/json/issues/313#issuecomment-298806623) show a 10% reduction in both build time and memory usage:
- 14.4 s → 13.0 s
- 451 M → 407 M
=> Reduce visitor-dependence in number parsers

.travis.yml, src/ser.rs
Now that Rust 1.18 has come out, and according to our policy of supporting
the past 3 versions of rust, we can finally switch to using
`char::encode_utf8` to encode a character into a string.
Closes #270.
=> Switch to using char::encode_utf8

src/de.rs, src/error.rs, tests/test.rs
**NOTE:** There is one small defect with this patch. The line and column numbers that the error message reports match the position of the closing brace after the trailing comma and not the position of the trailing comma.
I plant to continue searching for the logic that determines the line and column numbers. If someone wants to speed things up and point me towards the relevant code it would be much appreciated.
=> change error type for trailing commas, fixes #352

src/value/mod.rs
Clippy 0.0.166 doesn't trigger needless_pass_by_value lint when a trait bound satisfies both `T` and `&T` (so the caller can choose between them).
=> Remove unnecessary allow(needless_pass_by_value)

src/number.rs
Clippy fixed the bug in question.
=> Warn about enum_variant_names violations in enum N

src/de.rs
Fixes #386. According to [`cargo llvm-lines`](https://github.com/dtolnay/cargo-llvm-lines) this goes from 7728 lines of LLVM IR in `fix_position` to 92 lines.
=> Stop instantiating fix_position so many times

src/de.rs
The parse_value method is the most expensive method in serde_json in terms of compile time. Before this change, we were instantiating it twice for every derive(Deserialize) struct because every struct has two different Visitor impls -- one for the key type and one for the struct overall -- see https://serde.rs/deserialize-struct.html.
This improves compile time of [json-benchmark](https://github.com/serde-rs/json-benchmark) in release mode by 20%. #313
=> Stop instantiating parse_value in MapKey::deserialize_any

src/lib.rs
We only use our own error type; no need for From conversions provided by the standard library's try! macro. This reduces lines of LLVM IR by 4%. #313
=> Override the try macro to eliminate From calls

src/value/partial_eq.rs
This lowers us from 59 instantiations of Option::map_or to just 6. On my computer this improves serde_json compile time by about 5%. Pretty wild!
Fixes #391. Hopefully the real fix will be https://github.com/rust-lang/rust/issues/46758.
=> Fewer instantiations of Option::map_or

Cargo.toml
It now has a `std` feature, and uses `#![no_std]` otherwise.
cc #362
=> Update to num-traits 0.2 with no_std

src/error.rs, src/read.rs, tests/test.rs
A first pass at resolving #364.  Comments are welcome.
This patch checks specifically for control characters (ASCII 0x00 - 0x1F) in a JSON string and reports a more relevant error message:
```
control character (\u0000-\u001F) found while parsing a string at line 1 column 1"
```
Points of concern:
- There may be a better (i.e. shorter) error name than `ErrorCode::ControlCharacterWhileParsingString`.
- User confusion with error message.  Will a user suspect that escaped control characters caused the error because I mention the ASCII range formatted as escaped control characters?  Perhaps instead, I should say:
- `control character (ASCII 0x00 - 0x1F) found while parsing a string at line 1 column 1`, or
- `unescaped control character (\u0000-\u001F) found while parsing a string at line 1 …
=> Improve error when json strings contain control characters

src/de.rs, src/read.rs
=> Disambiguate `pos` meaning both "position" and "positive"

appveyor.yml
Fixes #308. This is copied from https://github.com/serde-rs/serde/pull/1135.
=> Get rustup-init with curl to avoid tls failures

Cargo.toml, src/lib.rs, src/number.rs
We do not require a crate to convert u64 to i64. Serde dropped its `num` dependency a long time ago in https://github.com/serde-rs/serde/pull/243.
=> Drop num-traits dependency

src/ser.rs
I think `char`s should be allowed to be `MapKey` or would that be in some way harmful?
I'm new to Rust and this repository seems really complex to me 😬.
Please let me know if and where I have to add/update tests – I'll be more than happy to do that!
=> Allow char to be a MapKey

src/macros.rs, tests/test.rs
The `unused_results` lint triggers on any function call returning anything other than `()` or `!` that is not used. The `Map::insert` function returns `Option<Value>` of the previous value of the inserted key.
Fixes #461.
=> Make json macro compatible with deny(unused_results)

src/macros.rs
@SergioBenitez I need to add a helper macro to `json_internal!` to pick up https://github.com/rust-lang/rust/pull/51496 and enable:
```rust
#![feature(use_extern_macros)]
use serde_json::json;
```
How would you like me to proceed? If it is is easier for rocket_contrib we could add an unused `json_internal_vec!` in one release, re-export it from rocket_contrib, then begin using it from `json_internal!` in another release.
=> Local inner macros

Cargo.toml, src/lib.rs, src/number.rs, src/ser.rs
This is a 35% improvement in the canada.json stringify-struct benchmark in [serde-rs/json-benchmark](https://github.com/serde-rs/json-benchmark) which involves serializing lots of f32. That benchmark time drops from 6.4 milliseconds with dtoa to 4.1 milliseconds with ryu.
cc @m-ou-se :heart:
=> Switch from dtoa to ryu

src/value/mod.rs
When building the documentation of `serde_json` with CommonMark (the default in Rust 2018), `rustdoc` will complain about a bare byte slice statement [u8]:
```
warning: `[u8]` cannot be resolved, ignoring it...
--> src/value/mod.rs:71:64
|
71 | //! [`from_slice`][from_slice] for parsing from a byte slice &[u8] and
|                                                                ^^ cannot be resolved, ignoring
|
= help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`
```
And ultimately resolving it to an erroneous HTML (the square brackets are gone):
```html
for parsing from a byte slice &<a href="https://doc.rust-lang.org/nightly/std/primitive.u8.html" title="u8">u8</a> and
```
I feel that backticks around the `&[u8]` should be enough to fix this.
=> Monospace format &[u8] in value module docs

src/ser.rs, src/value/de.rs, src/value/ser.rs
In preparation for #355, this is a small refactoring to make the machinery for "special" types (such as the arbitrary precision numbers) more reusable.
The problem with the existing implementation is that it introduces alternative method implementations in a few places, which means that with every additional special type the number of methods that need to be changed or introduced grows.
This refactor moves to a more extensible structure where new special types simply require additional `match` branches.
=> Refactor to make "special" type machinery more reusable

src/de.rs
This allocation dates back four years to:
- https://github.com/serde-rs/serde/commit/475fd5056460d2dcd5286a85ef0f7d748b3a9665#diff-9530295b7f43bb8787aa9fc51b4fba3dR1711
(subsequently touched in:
- https://github.com/serde-rs/serde/commit/20e642420ea346d9cac1c94c1cc6374a6851c3b9#diff-9530295b7f43bb8787aa9fc51b4fba3dR1711
- https://github.com/serde-rs/serde/commit/38dc9aaf72f85f4c1cb42da6d19b6d68839d28b8#diff-0058fb37bfb3827d38defff20282a80dR93
). That was back when *every* string, including map keys, was parsed one character at a time and accumulated into that pre-allocated buffer. So practically every input would require use of the buffer.
Nowadays with the serde_json::from_str optimization done in #105, strings are parsed in efficient fragments at a time and only require a side buffer in …
=> Remove pre-allocation in Deserializer construction

Cargo.toml, src/de.rs, src/lib.rs, src/number.rs, src/raw.rs, src/read.rs, src/ser.rs, src/value/de.rs, src/value/mod.rs, src/value/ser.rs, tests/test.rs
This PR builds on #480 but eliminates the `Cow` in favor of distinct `&RawValue` and `Box<RawValue>` options.
Documentation of `RawValue`:
---
Reference to a range of bytes encompassing a single valid JSON value in the input data.
A `RawValue` can be used to defer parsing parts of a payload until later, or to avoid parsing it at all in the case that part of the payload just needs to be transferred verbatim into a different output object.
When serializing, a value of this type will retain its original formatting and will not be minified or pretty-printed.
```rust
#[macro_use]
extern crate serde_derive;
extern crate serde_json;
use serde_json::{Result, value::RawValue};
#[derive(Deserialize)]
struct Input<'a> {
code: u32,
#[serde(borrow)]
payload: &'a RawValue,
}
#[derive(Serialize)]
struct …
```
=> Implement RawValue type (alternative)

src/de.rs, src/lib.rs, src/raw.rs, src/read.rs, src/ser.rs, src/value/de.rs, src/value/mod.rs, src/value/ser.rs, tests/test.rs
Implements the `RawValue` type described in #355. On [this benchmark](https://gist.github.com/srijs/7fe21b43c2cf5d2ceeb593ae4591c6f5), using the `RawValue` type instead of deserializing/serializing via `Value` results in a 3-4x speed-up.
```
test deserialize_and_serialize_raw_value ... bench:       1,759 ns/iter (+/- 354)
test deserialize_and_serialize_value     ... bench:       6,091 ns/iter (+/- 1,776)
```
I did not adhere fully to the way that the existing arbitrary precision feature is implemented, because I found it easier to use newtypes rather than structs to pass the raw data back and forth. If you want, I'm happy to either change it so that it uses the same approach as the arbitrary precision feature, or to change the arbitrary precision feature to use this (imo) simpler …
=> Implement RawValue type

.travis.yml, Cargo.toml, src/de.rs, tests/test.rs
Provides a method `disable_recursion_limit` to parse arbitrarily deep JSON structures without any consideration for overflowing the stack.
When using this method, the caller will want to provide some other way to protect against stack overflows, such as by wrapping the Deserializer in the dynamically growing stack adapter provided by the [serde_stacker] crate.
[serde_stacker]: https://github.com/dtolnay/serde-stacker
=> Unbounded depth

src/de.rs, tests/stream.rs, tests/test.rs
My attempt at fixing #524. First commit fixes that issue, the second commit also fixes a similar issue with truncated negative numbers ("-") and truncated exponents ("1e" and "1e+").
=> Return EOF on truncated numbers

src/de.rs
Today I stumbled across the fact that from_reader is slow. There seems to be a suggestion from back in 2016 to add a comment to the docs https://github.com/serde-rs/json/issues/160#issuecomment-258589916 but it seems it was never done. This PR finally adds that note as apparently people like me still stumble across the bug. See #160.
=> Add note about issue 160 to from_reader function

src/value/from.rs
Hey there,
this tiny PR adds the conversion from `()` to `Value::Null`.
I feel this is justified as serde_json already perceives `()` as the JSON value `null`:
```
println!("{:?}", serde_json::from_str::<()>("null"));
// prints `Ok(())`
println!("{:?}", serde_json::to_string(&()));
// prints `Ok("null")`
```
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0eac935756f3537acdf45486dcabb4db
Cheers,
Felix
PS: Please have a look at the marvelous signature of `<Value as From<()>>::from` :laughing:
=> Add `impl From<()> for Value`

Cargo.toml
The `preserve-order` feature uses `indexmap::map::OccupiedEntry::swap_remove` method which was only added in `1.2`, however, the `Cargo.toml` incorrectly requires `^1.0`.
=> Fix Required Minimum `indexmap` Version

src/value/de.rs, tests/test.rs
This allows users to deserialize from types like `HashMap<String, Value>`.
=> Implement IntoDeserializer for Value

src/value/mod.rs
I thought this might be a worthwile addition, as this, I think, is easier than `if let Some(v) = foobar.pointer_mut() {` followed by an assignment, which I've seen on GitHub a lot.
=> Add example for how to update value if one exists

README.md
As it seems to be the case as of latest commit (https://github.com/serde-rs/json/commit/4b8380261b63e0758877ab9cfe7ed1652cca4f88).
=> Update MSRV to 1.30 in README.md

.travis.yml, Cargo.toml, src/de.rs, src/error.rs, src/features_check/error.rs, src/features_check/mod.rs, src/io.rs, src/io/core.rs, src/io/mod.rs, src/iter.rs, src/lib.rs, src/map.rs, src/number.rs, src/raw.rs, src/read.rs, src/ser.rs, src/value/de.rs, src/value/from.rs, src/value/index.rs, src/value/mod.rs, src/value/partial_eq.rs, src/value/ser.rs
This builds up on #588 (thanks @Freax13!).
With this, we support `no_std` with `alloc` crate, starting from Rust 1.36 (this was done so that we can use it in WebAssembly environment but any such environment will work).
To minimize the noise, I tried to use the facade approach already used in Serde to provide some consistency between the two and improved on the `io` facade to work around it missing in `core`.
Thanks in advance for taking your time to review this and let me know if I can improve anything to help this land!
Closes #588. Closes #516.
=> Add a no_std/alloc feature

README.md
I forgot to include this as part of https://github.com/serde-rs/json/pull/606, sorry! I hope the wording is good enough.
=> Correct no-std support in README.md

CONTRIBUTING.md
The `test/deps` directory no longer exists, so I suspect these instructions are simply not necessary since the switch to `trybuild` in commit 8d7f731c2d70b1d2f03e42c1dc34d2ae778676e8.
=> Removing obsolete test instructions.

src/map.rs, src/ser.rs, src/value/ser.rs, tests/test.rs
The purpuse is to serialize serde_json::Map<> with other serializer like serde-xml-rs::to_writer(&mut writer, &json_value) that is not possible today. The problem is serde_json use only **map.serialize_key(k)** and **map.serialize_key(v)**. Some serializer can use only **map.serialize_entry(k, v)**. If we follow these advices :
https://docs.serde.rs/src/serde/ser/mod.rs.html#1778-1784
/// Serialize a map key.
///
/// If possible, `Serialize` implementations are encouraged to use
/// `serialize_entry` instead as it may be implemented more efficiently in
/// some formats compared to a pair of calls to `serialize_key` and
/// `serialize_value`.
and the implementation of serialize_entry : https://docs.serde.rs/src/serde/ser/mod.rs.html#1798-1826
We should use during the Map serialize use …
=> replace serialize key,value functions by serialize_entry

Cargo.toml
Relevant Serde PR: https://github.com/serde-rs/serde/pull/1620
To support both no-/std builds without using somewhat noisy
conditional compilation directives, we implement the re-exported
`serde::de::StdError` trait in https://github.com/serde-rs/json/pull/606.
However, this was only introduced in >= 1.0.100, so we need to bump
the version requirement of serde.
On the off chance of someone pulling in incompatible 1.0.4{5,6} versions
of serde_json, I believe it'd be good to yank those and cut a new
release with this patch.
Sorry for the omission in the original PR.
Fixes #612.
@dtolnay By the way, is there a chance a new version of `alt_serde_*` could be published? It'd help work around the Cargo feature bug, where accidentally pulling in `std` through build/dev dep for `no_std`/`alloc` …
=> Require serde >= 1.0.100 due to no_std-related Error re-export

src/value/mod.rs, src/value/ser.rs
This just makes `Serializer` public through a `pub use` in `serde_json::value`.
=> Expose `value::ser::Serializer`

src/map.rs
Our custom implementation of PartialEq was added in ffcafc9d35a8fb4765b58866acf5d0d05effa904 because LinkedHashMap's implementation was order dependent. When we later switched to IndexMap in 1c6d0ef3195082f9a7f864ba44241e46c998bb47 the implementation could have been simplified because it matches https://github.com/bluss/indexmap/blob/1.0.0/src/map.rs#L1684-L1697.
=> Simplify Map's PartialEq impl

src/ser.rs
Previously this would go through the default implementation which does memory allocation.
https://github.com/serde-rs/serde/blob/v1.0.105/serde/src/ser/mod.rs#L1358-L1366
=> Implement collect_str for map keys

src/map.rs, src/read.rs, src/ser.rs, src/value/index.rs, src/value/ser.rs
```diff
- fn serialize_field<T: ?Sized>(&mut self, value: &T) -> Result<()>
+ fn serialize_field<T>(&mut self, value: &T) -> Result<()>
where
-     T: Serialize,
+     T: ?Sized + Serialize,
{
```
These are left over from Rust 1.14 or older, before `?Sized` was supported in where-clauses.
=> Move ?Sized bounds out of generic parameter lists

src/map.rs, src/value/de.rs, src/value/ser.rs
Some tweaks to make the following produce a more compact error.
```toml
[dependencies]
serde_json = { version = "1.0", default-features = false }
```
```console
error: expected item, found `"serde_json requires that either `std` (default) or `alloc` feature is enabled"`
--> src/features_check/error.rs:1:1
|
1 | "serde_json requires that either `std` (default) or `alloc` feature is enabled"
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected item
```
```console
error: expected item, found `"serde_json requires that either `std` (default) or `alloc` feature is enabled"`
--> src/features_check/error.rs:1:1
|
1 | "serde_json requires that either `std` (default) or `alloc` feature is enabled"
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
```
=> Improve error message when neither std nor alloc is enabled

src/map.rs, src/number.rs, src/value/mod.rs
These types already have `PartialEq` implementations which define equivalence relations, so we can implement `Eq` as well. Fixes #638.
=> Implement Eq for Map, Number and Value.

src/raw.rs, src/value/mod.rs
Resolves #654.
I adopted the `# Errors` doc section from `to_value`. I can also try coming up with a semi-realistic example of how one would use this.
=> Add value::to_raw_value

tests/crate/test.rs
Tested with:
```
cargo check \
--manifest-path tests/crate/Cargo.toml \
--target aarch64-unknown-none \
--no-default-features \
--features alloc
```
which fails before this commit and succeeds after.
Before this commit:
```console
Checking serde_json_test v0.0.0
error[E0463]: can't find crate for `std`
|
= note: the `aarch64-unknown-none` target may not be installed
error: aborting due to previous error
```
=> Support verifying no-std support through serde_json_test

Cargo.toml, src/de.rs, tests/test.rs
This is a new attempt at fixing issue #536 using the latest version of @Alexhuszagh 's `minimal-lexical` library for deserialization of f64 values. The goal is to make float roundtrip work without severely impacting compile times.
I have:
- checked that the crate still compiles with Rust 1.31
- added a sample of roundtrip tests that fail with the current deserializer but pass with this branch (also did some testing with `quickcheck` but didn't add that here as it would bring it a new dev-dependency)
- ran [this loop test](https://github.com/serde-rs/json/issues/536#issuecomment-583708730) for over 45 minutes
- measured changes in compile time using `perf` (see table below)
- benchmarked this branch and compared it against master (results at the bottom)
Note that:
- as used here (with …
=> tweak f64 deserialization to make float roundtrips work

src/macros.rs, tests/ui/missing_comma.rs, tests/ui/missing_comma.stderr, tests/ui/parse_expr.stderr
https://github.com/rust-lang/rust/issues/73777
=> Prevent type ascription misdiagnosis

README.md
This helps prevent a common problem (#564, #682) caused by not including `features = ["derive"]` and getting `cannot find derive macro `Serialize` in this scope` compiler error.
=> Linked ReadMe to Using Derive page.

src/read.rs
Add Read implementation for &mut Read. Because of the `Sealed` trait, we can't implement `Read` in other create.
This kind of trick is required if we want to build a streaming implementation (like asked in https://github.com/serde-rs/json/pull/526, https://github.com/serde-rs/json/pull/665) in another crate :
We can't use `serde_json::Deserializer` because we need to give it the Read object the streaming deserializer is working with and there is no way to get it back.
=> Add Read implementation for &mut Read

src/value/from.rs
=> Add impl From<Number> for Value

src/de.rs
This seem to be what is now expected on stable; as the compiler warnings are saying; and also consistent with what `read_user_from_stream` example is using.
=> Update example to use Result<User, Box<dyn Error>>

src/value/mod.rs
Since the serializer only emits valid utf8 [by default](https://github.com/serde-rs/json/issues/750) we can remove the checks that the data being formatted is valid.
`WriterFormatter` has been moved into it's own little module to enforce using it's `new` method to convey the unsafe requirements.
the safety requirements that the serializer only emits valid utf8 is already assumed by the existing `to_string` methods.
Marking `WriterFormatter` as unsafe is not strictly necesarry as it is already contained within the module bounds, but this way it's a bit more explicit about the assumptions being made.
this speeds up formatting large `Value`s by about 33% in my testing.
=> use from_utf8_unchecked in the fmt::Display implementation of Value

src/de.rs
The `from_bytes` has been removed. The document is outdated.
=> Fix method document in de.rs

src/map.rs
Like `std::collections::hash_map::Entry`, I guess the `Entry` defined in this crate can provide `and_modify`.
=> Add Entry::and_modify

src/read.rs, tests/test.rs
=> Fix panic deserializing RawValue from invalid utf-8 bytes

src/value/mod.rs
By using Iterator::try_fold, we don't need to go a roundabout route for borrow checker anymore.
=> Refactor Value::pointer_functions by using Iterator::try_fold

README.md
Seems like the project moved to a new location, and the old one returns 404.
=> Update link to serde-json-core

README.md
Run-in-playground and Copy-to-clipboard were overlapping.
=> Overlapping button fix

.github/workflows/ci.yml, Cargo.toml, src/de.rs, src/lib.rs, src/raw.rs, src/read.rs, src/ser.rs
I think this will make it much easier to tell at a glance that the `RawValue` API is not provided by default. While I was at it, I also added the attribute for other things where it seemed to make sense. Let me know what you think!
=> Make use of nightly doc_cfg on docs.rs

src/de.rs, tests/test.rs
Fixes #785.
Now the exact representation of the input JSON is preserved in the internal representation, and thus really makes "JSON -> Number -> JSON" produce output identical to the input (as described in [Cargo.toml](https://github.com/serde-rs/json/blob/ea39063f9c8c7dde4ac43bbd9843287bece59b1a/Cargo.toml#L71)).
=> Make arbitrary_precision preserve the exact string representation

src/value/de.rs
Only the `deserialize_any` method of this impl was ever invoked, which can be handled more simply.
=> Delete Deserializer impl from value::‍de::MapDeserializer

src/value/de.rs, tests/regression/issue795.rs
=> Detect unknown struct variant fields deserializing from Value

Cargo.toml, src/number.rs, tests/test.rs
This is the minimal version of my previous PR #790. I implemented the `Eq` and `Hash` traits for the `Number` type, regardless of its definition. Contrarily to my previous PR, this is strictly limited to the `Number` type.
I was originally going to use the `ordered_float` crate for that, but it turns out it is much simpler to do it manually. It avoids a dependency, and this library is not compatible with Rust 1.31.0 because it uses const parameters somewhere in the code of an optional feature, which has a syntax that is not supported with this version of Rust.
I had to manually implement `PartialEq` for `Number` to please clippy.
=> Implement `Hash` for `Number`.

build.rs, src/map.rs, tests/map.rs
This adds the `retain` function to the Map type which calls the inner
maps, Either `indexmap` or std `BTreeMap`'s, retain.
I'm trying to mutate a `Value::Object`'s Map in-place and could't find a
nice way without the `retain` function.
These new `retain` functions will also only be included when compiling with Rust 1.53.0+ when `retain` was added to the BTreeMap in the std lib https://blog.rust-lang.org/2021/06/17/Rust-1.53.0.html#stabilized-apis
=> Add retain to Map

src/map.rs
I have added the `get_key_value` method to the `Map` type. This is useful to get a reference to the matched key that lives as long as the map.
=> Add `Map::get_key_value` method.

src/raw.rs
Similar to the std `impl From<Box<str>> for Box<[u8]>`:
https://doc.rust-lang.org/std/boxed/struct.Box.html#impl-From%3CBox%3Cstr%2C%20A%3E%3E
Use case: https://github.com/tokio-rs/axum/pull/509
=> Add impl From<Box<RawValue>> for Box<str>

src/de.rs, src/read.rs, tests/test.rs
This commit deserializes lone surrogates in strings that are encoded in
escape sequences instead of erroring on them.
As per https://github.com/serde-rs/json/issues/827#issuecomment-976983620
---
Note the implementation here is ugly & unoptimized. I'll go fix this after
an initial review of the functionality.
=> Deserialize lone surrogates into byte bufs

src/read.rs
For `n: u16` where `0xD800..=0xDBFF` and `0xDC00..=0xDFFF` have already been handled, the conversion `char::from_u32(n as u32)` can't fail.
```rust
for n in 0..=u16::MAX as u32 {
let expected_is_okay = n < 0xd800 || n > 0xdfff;
let actual_is_okay = char::from_u32(n).is_some();
assert_eq!(expected_is_okay, actual_is_okay);
}
```
=> Skip error codepath on hex escape outside the surrogate range

src/raw.rs, tests/test.rs
Currently, we cannot creating `RawValue` from `&str` using `serde_json::value::to_raw_value` since the function requires `Sized` implicitly. This PR removes this restriction.
=> Allow creating `RawValue`s from references to unsized values

src/de.rs, src/lib.rs, tests/regression/issue845.rs, tests/test.rs
=> Deserialize small numbers as integers in arbitrary_precision

src/read.rs, tests/test.rs
See https://github.com/serde-rs/json/issues/827#issuecomment-979208987﻿
=> Allow lone surrogates in raw values

Cargo.toml
`indexmap`'s use of `autocfg` doesn't always properly detect `std`, which is needed if you're using the default `S` hasher. The "indexmap/std" feature will explicitly force it on.
This does mean that `preserve_order` requires `std`, but that was already effectively true by using the default `S`. Alternatively, we could pick a `no_std` hasher crate for this, or implement a simple one locally.
=> Explicitly enable indexmap/std

src/error.rs, src/map.rs, src/read.rs, src/ser.rs, src/value/de.rs, src/value/index.rs, src/value/mod.rs, src/value/ser.rs
`ref` is largely superseded by "match ergonomics" in modern versions of Rust.
=> Eliminate all use of ref keyword

src/value/from.rs
Adds an implementation for `From<Option<T>>` for all `T` where `T: Into<Value>`
Use case: Ergonomics for manually constructing values for insertion into `BTreeMap` (sentry does this)
I have no idea where / how the tests happen. If this is an acceptable change, could someone point me in the direction of the tests?
=> Make Value be From<Option<T>>

src/number.rs, src/value/mod.rs, tests/debug.rs
**Before:**
```rust
println!("{:#?}", value);
```
```rust
Object({
"Array": Array([
Bool(
true,
),
]),
"Bool": Bool(
true,
),
"EmptyArray": Array([]),
"EmptyObject": Object({}),
"Null": Null,
"Number": Number(
1,
),
"String": String(
"...",
),
})
```
**After:**
```rust
Object {
"Array": Array [
Bool(true),
],
"Bool": Bool(true),
"EmptyArray": Array [],
"EmptyObject": Object {},
"Null": Null,
"Number": Number(1),
"String": String("..."),
}
```
=> Reduce unneeded parens and newlines in Debug for Value

src/number.rs, tests/debug.rs
Tiny followup to #918.
```rust
let number: serde_json::Number = serde_json::from_str("1.0").unwrap();
println!("{}", number);
```
Previously: `1`
Now: `1.0`
=> Preserve '.0' when Displaying Number

src/number.rs
The feature `arbitrary_precision` didn't compile without the feature `std` enabled. Let's fix it.
=> arbitrary_precision without std

src/ser.rs
`itoa` natively and unconditionally supports `i128` and `u128`, so we can use it instead of `to_string` on those types.
This change should have no publicly visible behavior changes. It was previously impossible to customize behavior for 128 bit ints in `Formatter`, so there aren't any public facing behavior changes introduced by the addition of new methods to `Formatter`.
The MSRV for `serde_json` is 1.36, so there should be no need to conditionally compile anything in this MR. This is affirmed by the `itoa` dependency, which unconditionally supports 128 bit integers.
=> Add direct support for i128 and u128 via itoa

Cargo.toml, README.md, src/lib.rs
Back when `features = ["alloc"]` got added, serde_json with default features supported Rust 1.30, so it made sense to call out that alloc was limited to a more recent compiler than that. Now only 1.36+ is supported in general so alloc is no longer special.
=> Delete 1.36+ caveat from descriptions of alloc feature

src/de.rs, src/number.rs, src/ser.rs, src/value/de.rs, src/value/from.rs, src/value/ser.rs
According to https://github.com/serde-rs/serde/blob/v1.0.145/serde/build.rs#L57-L62, it's false on Emscripten older than 1.40 and other targets older than 1.26. Since serde_json currently requires Rust 1.36 or newer, the only effect is dropping support for using Emscripten with Rust 1.36, 1.37, 1.38, 1.39, which are 3-year-old compilers that nobody has any reason to use when building for Emscripten today, given how premature the support for Emscripten was at the time.
=> Assume serde_if_integer128 is true

src/map.rs
This PR adds `clone_from` to `Map`'s `Clone` implementation, so that clones can take advantage of existing storage. Additionally, `Map::append` now uses `IndexMap::extend`, to take advantage of reservation logic.
=> Add clone_from and use IndexMap::extend

src/raw.rs
Work around this rustdoc issue: https://github.com/rust-lang/rust/issues/90435.
=> Hide repr attribute from documentation

src/error.rs
Fixes #991.
The same code in the issue now produces:
```console
Error: bad read
Caused by:
timed out waiting on channel
```
=> Fix message duplication between error Display and source()

src/number.rs, src/value/from.rs, src/value/partial_eq.rs, src/value/ser.rs, tests/regression/issue1004.rs
Fixes #1004.
"Arbitrary precision" needs to mean "arbitrarily low precision", too.
=> Eliminate f32-to-f64 casting in arbitrary_precision mode

src/de.rs, src/error.rs, src/io/core.rs, src/ser.rs
Previously the documentation used an inconsistent mix of "I/O" and "IO".
"I/O" is the spelling used by the std::io module documentation: https://doc.rust-lang.org/1.70.0/std/io/index.html.
Wikipedia also prefers "I/O", with "IO" listed only as an informal spelling. <https://en.wikipedia.org/wiki/Input/output> _"input/output (I/O, i/o, or informally io or IO)"_
=> Standardize on "I/O" instead of "IO"

src/error.rs
=> Add Error::io_error_kind

src/ser.rs
This PR updates `MapKeySerializer::serialize_some` to match `Serializer::serialize_some`.
Currently, all calls to `serialize_some` are rejected with the `key_must_be_a_string` error that many other variants use. Because there is no distinction between `Some(T)` and `T` in JSON, I think that serializing the underlying type directly is a better behavior for this function.
I think this change is useful for serializing types that have internal nullability. In a project I am working on, there is a bitpattern in a type I am serializing that I would like serialize as `null`. To behave correctly with as many serializers as I can, I use `serialize_some` and `serialize_none`. When the type is used as a key, this causes serde_json to panic, even if the value is normally fine as a key.
One argument …
=> Support MapKeySerializer::serialize_some

src/de.rs, src/error.rs, src/ser.rs, src/value/de.rs, src/value/ser.rs, tests/test.rs
Now we allow objects with `f32` or `f64` string-serialized keys. For example:
```json
{ "1.123": "foo", "2.0": "bar" }
```
The `test_deny_float_key` test has been inverted, and the `deserialize_integer_key` macros have been renamed to `deserialize_numeric_key` in order to support `f32` and `f64`.
=> Allow `f32` and `f64` map keys

src/ser.rs
Example that writes bytes as base64 JSON strings:
```rust
// [dependencies]
// base64 = "0.21"
// serde = { version = "1", features = ["derive"] }
// serde_bytes = "0.11"
// serde_json = "1"
use serde::Serialize;
use std::io::{self, Write};
#[derive(Serialize)]
struct Struct {
#[serde(with = "serde_bytes")]
buf: Vec<u8>,
}
struct Base64Formatter;
impl serde_json::ser::Formatter for Base64Formatter {
fn write_byte_array<W>(&mut self, writer: &mut W, value: &[u8]) -> io::Result<()>
where
W: ?Sized + io::Write,
{
writer.write_all(b"\"")?;
let engine = &base64::engine::general_purpose::STANDARD_NO_PAD;
let mut encoder = base64::write::EncoderWriter::new(writer, engine);
encoder.write_all(value)?;
let writer = encoder.finish()?;
writer.write_all(b"\"")
}
}
fn main() -> serde_json::Result<()> { …
```
=> Add Formatter::write_byte_array

src/de.rs, src/ser.rs, src/value/de.rs, src/value/ser.rs, tests/test.rs
=> Support bool in map keys

src/value/mod.rs
Resolves #1068 by adding `as_number` to `Value`.
=> adds `as_number` to `Value`

src/number.rs
Resolves #1066 by adding `as_str` to `Number` if `arbitrary_precision` is enabled.
I'm sorry this is a silly question but where should I put tests for the method?
=> adds `as_str` to `Number` if `arbitrary_precision` is enabled

src/raw.rs
```rust
use std::collections::BTreeMap;
fn main() {
let j = r#" {"x": {"k": "v"}} "#;
let deferred: BTreeMap<&str, &serde_json::value::RawValue> = serde_json::from_str(j).unwrap();
let x: BTreeMap<&str, &str> = serde::Deserialize::deserialize(deferred["x"]).unwrap();
println!("{:?}", x);
}
```
=> Support deserializing from &RawValue

src/value/from.rs, src/value/index.rs, src/value/partial_eq.rs
These don't appear necessary and tests pass locally.
=> Remove a few unnecessary lifetimes

tests/test.rs
New clippy lint from Rust 1.75: https://rust-lang.github.io/rust-clippy/rust-1.75.0/index.html#/manual_hash_one
=> Resolve manual_hash_one lint in test

src/de.rs, src/lib.rs, src/value/mod.rs
This regressed with https://github.com/rust-lang/rust/pull/113091 in nightly-2023-12-16. The doc(cfg()) from the type definition is no longer rendered.
=> Restore doc cfg on re-exports

src/lexical/num.rs
fix: Correct the only spelling error
After scanning the entire repository, I discovered the only spelling error and fixed it.
- Changed "exponet" to "exponent"
=> fix: Correct spelling error

src/error.rs
This produces a more readable representation using exponential notation for values that might be hundreds of digits when formatted by std::fmt.
It also includes trailing `.0` on integer values (https://github.com/serde-rs/serde/pull/2679).
=> Format f64 in error messages using ryu

src/raw.rs
This used to be needed prior to https://github.com/rust-lang/rust/pull/115439.
=> Remove conditional on repr(transparent)

README.md, src/lexical/large_powers32.rs, src/lexical/large_powers64.rs, src/lib.rs, src/read.rs
While reading the documentation/the source code (for the purpose of creating my own `Deserializer` for a different format) I found that in [`serde_json::de::Read`](https://docs.rs/serde_json/latest/serde_json/de/trait.Read.html) `&[u8]` was rendered incorrectly.
So I did a quick `grep` and fixed all I could find by adding backticks.
I also switching the `&[u8]` in the `README.md`/`src/lib.rs` from escapes to backticks for consistency sake. \
(I assume the `README.md` was generated from the `src/lib.rs` with some tool, but if both are changed the same way, it should still be consistent with the output.)
=> Fix missing backtick in doc comments letting markdown think &[u8] is a link to u8

Cargo.toml
As of recently, docs.rs defines a `docsrs` configuration for all builds, so we no longer need to do it using our own `package.metadata.docs.rs.rustdoc-args`.
=> Rely on docs.rs to define --cfg=docsrs by default

src/map.rs, src/value/mod.rs
`IndexMap` is the only type that is used within `Value` that does not implement `Hash`, and it is by design: https://github.com/indexmap-rs/indexmap/issues/288#issuecomment-1804735361
If "preserve_order" feature is not set, `Value::Object` uses `BTreeMap` instead of `IndexMap` so it is possible to auto-impl `Hash` for `Value`.
=> impl `Hash` for `Value`

src/map.rs, tests/map.rs
This method inserts a key-value pair in the map at the given index. If
the map did not have this key present, `None` is returned. If the map
did have this key present, the key is moved to the new position, the
value is updated, and the old value is returned.
This is useful when you want to insert a key-value pair at a specific
position in the map, and is a necessary method when writing a JSON
editor that can mutate the keys in a JSON object.
This is only enabled when the preserve-order feature flag is enabled.
```rust
map.shift_insert(0, "foo", "bar")
```
Mirrors the logic in [`IndexMap::shift_insert()`](https://docs.rs/indexmap/2.2.6/indexmap/map/struct.IndexMap.html#method.shift_insert)
=> Add Map::shift_insert()

Cargo.toml
PR #1149 introduced `Map::shift_insert()` but version of `indexmap` stayed on `2.2.1` which doesn't have this, causing issue on build where `serde_json` is used as a dep.
Updating dep to minimal version of `2.2.3`
(Let me know if it should be `2.2.6` because it's the version in the lock)
=> fix: indexmap minimal version with Map::shift_insert()

src/value/index.rs
The current id doesn't exist, so the link just goes to the top of the docs for Value, rather than to the intended section covering `impl<I> Index<I> for Value`.
=> Correct documentation URL for Value's Index impl.

src/de.rs
As far as I can see, all uses of `check_recursion!` except this one don't early-return. The current code decreases `remaining_depth` but doesn't increase it back on visit failure. I don't have a test, but this is probably a bug.
=> Move call to tri! out of check_recursion!

Cargo.toml, src/read.rs
Translating index into a line/column pair takes considerable time. Notably, the JSON benchmark modified to run on malformed data spends around 50% of the CPU time generating the error object.
While it is generally assumed that the cold path is quite slow, such a drastic pessimization may be unexpected, especially when a faster implementation exists.
Using vectorized routines provided by the memchr crate increases performance of the failure path by 2x on average.
Old implementation:
```
DOM         STRUCT
data/canada.json        122 MB/s    168 MB/s
data/citm_catalog.json  135 MB/s    195 MB/s
data/twitter.json       142 MB/s    226 MB/s
```
New implementation:
```
DOM         STRUCT
data/canada.json        216 MB/s    376 MB/s
data/citm_catalog.json  238 MB/s    736 MB/s
data/twitter.json …
```
=> Optimize position search in error path

src/macros.rs, tests/ui/missing_colon.stderr, tests/ui/missing_value.stderr
The syntax of using a path to call a macro has been stable since Rust 1.30. These days serde_json no longer supports anything older than Rust 1.56.
=> Eliminate local_inner_macros in favor of non-ident macro paths

src/lib.rs, src/macros.rs
=> Fix `json!` invocations when std prelude is not in scope

src/lib.rs, src/read.rs, tests/test.rs
I've implemented [your suggestion here](https://github.com/serde-rs/json/pull/1160#pullrequestreview-2203573484), and I need a bit of your input regarding my approach.
What we *really* want is to find the first character s.t. `ch == b'"' || ch == b'\\' || ch < 0x20`. memchr3 supports searches of kind `ch == a || ch == b || ch == c`, which is almost what we need. SIMD comparisons for equality and non-equality are not significantly different performance-wise or implementation-wise, so memchr could theoretically help us out. I've filed https://github.com/BurntSushi/memchr/issues/157, but chances are this isn't going to be implemented anytime soon.
The second best thing -- and I want to articulate that this is *not* the more performant solution -- is to first use SIMD to scan for `"` or `\` …
=> Vectorize string parsing

src/read.rs, tests/test.rs
I have belatedly realized that using `leading_zeros` does not, in fact, work on big-endian machines. I have updated the test to trigger the failure (reproduce with `cargo miri test --test test --target powerpc64-unknown-linux-gnu test_control_character_search`) and switched to the slower-but-correct `from_le_bytes` method instead.
=> Oops, fix skip_to_escape on BE architectures

.github/workflows/ci.yml
It's not that we care about any particular set of architectures. These jobs were added because we care about coverage in different endianness and pointer size.
**Before:**
<p align="center"><img src="https://github.com/user-attachments/assets/f446ef3c-ce7d-424d-8099-bc45cbdf2f2d" width="600"></p>
**After:**
<p align="center"><img src="https://github.com/user-attachments/assets/e77874ab-d26b-4229-8a9c-76494bef9281" width="600"></p>
=> Improve job names for miri jobs

src/read.rs, tests/test.rs
When ignoring *War and Peace* (in Russian), this increases performance from 640 MB/s to 1080 MB/s (+70%).
When parsing into String, the savings are moderate but still significant: 275 MB/s to 320 MB/s (+15%).
=> Parse \uXXXX escapes faster

src/de.rs, src/read.rs, tests/test.rs
Previously #828 added support for deserializing lone leading and
trailing surrogates into WTF-8 encoded bytes when deserializing a string
as bytes. This commit extends this to cover the case of a leading
surrogate followed by code units that are not trailing surrogates. This
allows for deserialization of "\ud83c\ud83c" (two leading surrogates),
or  "\ud83c\u0061" (a leading surrogate followed by "a").
The docs also now make it clear that we are serializing the invalid code
points as WTF-8. This reference to WTF-8 signals to the user that they
can use a WTF-8 parser on the bytes to construct a valid UTF-8 string.
Follow up to https://github.com/serde-rs/json/pull/830#pullrequestreview-880820431.
=> Deserialize invalid UTF-8 into byte bufs as WTF-8

src/de.rs, src/read.rs, tests/test.rs
Altogether, this speeds up \u-encoded War and Peace parsing by 20%. Performance on json-benchmark is slightly affected: there are some 5% improvements and a -1% regression, but I'm willing to write that off as noise from an imperfect benchmark setup.
This PR should be more readable per-commit w/o whitespace changes. In addition to the above, it includes a variation on #877, since it's easier to implement with this design.
=> Speed up \uXXXX parsing and improve WTF-8 handling

src/read.rs
This removes two instructions (tops) and frees up one register. This is really, really stupid, and probably does not affect performance in practice (It does on the memory-bound War and Peace benchmark though. By 1%.), but I couldn't stop myself from patching this when I read the code with a fresh mind. Sorry.
=> Optimize Unicode decoding by 1% 🤡

src/read.rs
Various architectures have native support for 64-bit integers, but there are Rust targets for those architectures where the pointer size is intentionally just 32-bit. For SWAR this smaller pointer size would negatively affect those targets, so this PR ensures the chunk size stays 64-bit on those targets.
The same is done in various other crates, such as [hashbrown](https://github.com/rust-lang/hashbrown/blob/f1ba3b4547f5a8f0d4b679e4f44298138d89be59/src/raw/generic.rs#L10-L15). Though I wish there was some sort of `#[cfg(target_integer_width = "64")]`.
=> Ensure the SWAR chunks are 64-bit in more cases

src/map.rs
`serde_json::Map` has several methods for removing an entry:
- `.remove(key)`
- `.swap_remove(key)` (with preserve_order)
- `.shift_remove(key)` (with preserve_order)
- `.remove_entry(key)`
- `.swap_remove_entry(key)` (with preserve_order)
- `.shift_remove_entry(key)` (with preserve_order)
But poor `serde_json::map::OccupiedEntry` only has `.remove()`.
This means we can't easily/efficiently get the owned key from an `OccupiedEntry` - we have to either borrow and clone it, or call `.remove_entry(key)` on the original map, which will re-hash the key. Neither of these are catastrophic, but it's extra work we can avoid, since the underlying `OccupiedEntry` for both `BTreeMap` and `IndexMap` have a `remove_entry` method.
Similarly, with preserve_order enabled, we can't easily remove the entry …
=> Add more removal methods to `OccupiedEntry`

src/value/ser.rs
Now `HashMap` doesn't support i128/u128 key serialization (deserialization works). 
Example of code:
```rust
let mut b = HashMap::new();
b.insert(0_i128, String::new());
serde_json::to_value(b).unwrap();
```
Error:
```bash
Error("i128 is not supported", line: 0, column: 0)
```
I don't find any reason why. So I added the missing methods.
=> Add support for 128 bit HashMap key serialization

src/map.rs, src/value/mod.rs
=> Add methods on Map and Value to destroy preserved ordering

src/number.rs, src/value/de.rs, src/value/mod.rs
Implemented serde::de::Visitor::visit_i128.
This fixes compatability with Ipld::Integer when using DagJsonCodec.
=> Add i128 deserialization

src/number.rs
Followup to https://github.com/serde-rs/json/pull/1141. There is no value of i128 for which u64::try_from returns Err **and** i64::try_from returns Ok **and** &gt;=0.
=> Delete unreachable branch from Number::from_i128

src/value/de.rs
Followup to https://github.com/serde-rs/json/pull/1141.
=> Return error instead of Null if i128 deserialized to Value is out of range

src/map.rs, src/value/de.rs
This PR adds `Deserializer` impls for `Map<String, Value>` and `&Map<String, Value>` and `IntoDeserializer` impls for the same. The first commit moves the relevant code from the value `Deserializer` impl into the new map impls. The last two are some small cleanups to use the map deserializer impl directly.
I put the `Deserializer` trait impls in `src/value/de.rs` so that they can reuse the existing helpers there. If you would prefer that they go elsewhere I am happy to move them.
Closes #1134
=> Implement `Deserializer` for `Map<String, Value>` and `&Map<String, Value>`

src/de.rs
Measured in https://github.com/serde-rs/json-benchmark using `cargo llvm-lines --bin json-benchmark --no-default-features --features parse-struct,lib-serde,all-files --filter 'next_element_seed|next_key_seed'`, this PR reduces LLVM lines by 53% (compared to 37% for #1102). This is the part of the logic that needs to be instantiated separately per seq/map type, as opposed to once per Read type.
Across the whole json-benchmark program, this PR decreases total LLVM lines by 8.8% (compared to 5.6% for #1102) and decreases function instantiations by 3.4%.
Benchmarked using `cargo build --release --bin json-benchmark --no-default-features --features parse-struct,lib-serde,all-files`, there is no statistically significant performance difference at runtime. (But I notice some opportunities to …
=> Reduce duplicative instantiation of logic in SeqAccess and MapAccess

src/read.rs
I noted the lack of a comment when performing a review. The implementation is safe, just not documented.
=> Add a safety comment to unsafe block

src/raw.rs
I have been using `RawValue` a lot lately to implement server endpoints that accept large JSON objects, extract some specific fields and  ultimately save the entire JSON to the DB.
As part of this process, a proc-macro based JSON pre-processor is used to automate HTTP error responses. This also uses `RawValue` to avoid allocating when traversing unknown JSON data.
The pre-processor uses literal "null"'s as part of it's logic, and at the moment I'm deserializing a literal `"null"` string to `RawValue` every time I need one.
This could be done once and stored in a `LazyLock` or something similar, but I thought that adding literal values to the `RawValue` struct is the least complex solution.
What do you think?
=> Add literal 'null', 'true' and 'false' consts to `RawValue` struct.

src/raw.rs
| Before | After |
|---|---|
| <img src="https://github.com/user-attachments/assets/3e1b772d-b31b-4486-bf4c-9344c905c81e" width="400"> | <img src="https://github.com/user-attachments/assets/78aec3d1-a9e6-4aa7-b4ed-eb4d6038f642" width="400"> |
=> Move RawValue associated constants into same impl block as public functions

src/map.rs
=> Add Map::into_values method

src/ser.rs
This matches equivalent documentation on `ryu::Buffer::format_finite`.
https://docs.rs/ryu/1.0.19/ryu/struct.Buffer.html#method.format_finite
=> Document behavior of write_f32/f64 on non-finite floats

.github/workflows/ci.yml
I do not know why #1174 added these steps. [They are not present in the semver crate](https://github.com/dtolnay/semver/blob/1.0.23/.github/workflows/ci.yml#L103-L110), which also tests with miri on the same set of platforms.
The `gcc-powerpc-linux-gnu` installation has been failing in CI since February 27 with this 404 error:
```console
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
binutils-powerpc-linux-gnu cpp-13-powerpc-linux-gnu cpp-powerpc-linux-gnu
gcc-13-cross-base gcc-13-powerpc-linux-gnu gcc-13-powerpc-linux-gnu-base
gcc-14-cross-base libasan8-powerpc-cross libatomic1-powerpc-cross
libc6-dev-powerpc-cross libc6-powerpc-cross libgcc-13-dev-powerpc-cross
libgcc-s1-powerpc-cross …
```
=> Delete unused gcc installation

src/read.rs
=> chore: fix typo

src/ser.rs
While serializing strings, we enter the hot loop checking 1 byte at a time. By massaging the code and using a little bit of unsafe, we can optimise this hot loop a bit.
<details>
<summary>This benchmark shows about a 2-5% speedup when working with string heavy documents</summary>
Benchmark was run with target x86_64-unknown-linux-gnu on an Intel Xeon Platinum 8375C CPU @ 2.90GHz, as well as on an Apple M4 Max.
```rust
use std::hint::black_box;
use criterion::{criterion_group, criterion_main, Criterion};
use serde_json::Value;
pub fn k8s(c: &mut Criterion) {
// https://raw.githubusercontent.com/kubernetes/kubernetes/v1.33.3/api/openapi-spec/swagger.json
let k8s = std::fs::read_to_string("benches/k8s-openapi.json").unwrap();
let value: Value = serde_json::from_str(&k8s).unwrap();
drop(k8s); …
```
=> string serialization escaping optimisations

src/value/mod.rs
A rounded edge for:
```
let val: Value;
val.pointer("/foo).unwrap_or_default()
```
Obviously not required.
=> feat: impl Default for &Value

src/map.rs
I've noticed that the iterators for `Map` are missing some traits that are implemented by their counterpart in `std::collections` and `indexmap`: namely, `Clone` and `Debug`. AFAICT, there's no reason for those to be missing, and they can be useful. I found myself missing `Clone` on `Iter`, for example.
Initially, I'd included `Default` among these, but it's not supported on Rust 1.65 and older.
=> Add Clone and Debug impls to map iterators

src/value/de.rs
My use case is to enable:
```rust
#[cfg_attr(feature = "clap", arg(long))] // <- clap requires one of From<OsString>, ... , FromStr
#[cfg_attr(feature = "serde", serde(default))]
pub whatever: Option<serde_json::Map<String, serde_json::Value>>,
```
I could write a value_parser for clap:
```rust
fn parse_json_object(s: &str) -> Result< serde_json::Map<String, serde_json::Value>, String> {
serde_json::from_str(s).map_err(|error| error.to_string())
}
```
But that probably isn't doing the best job with respect to error formatting.
=> Implement `FromStr` for `Map<String, Value>`
